### PR TITLE
isolate settings context before first test

### PR DESCRIPTION
**Pull request by rababerladuseladim**
# PR Context
- blocked by: https://github.com/robert-koch-institut/mex-extractors/pull/39 as testing is only possible after the mex-common dependency in mex-extractors is updated to v0.24.0
- Bug: the first test that is executed does not receive isolated settings. It therefore receives the production data as they are in mex-assets. If the test uses data from mex-assets, it will get a different result than if it is not executed first.
- Reproduce: in mex-extractors, execute `pdm run pytest .\tests\sumo\test_extract.py::test_extract_cc1_data_model_nokeda`
  - passes if not executed as first test
  - fails if executed in isolation / as first test

# Fixed
- isolate settings context before first test

### CODE REVIEW

**Review by erichesse — COMMENTED** [review]
I can confirm the bug, I couldn't confirm the fix. when I install `mex-extractors` witht `"mex-common@git+https://github.com/robert-koch-institut/mex-common.git@0.24.0@hotfix/isolate-settings-context-before-first-test"` in `pyproject.toml`, the error seems to persist. How did you test the fix?

Also, should there also be a hotfix version be bumped for `mex-common?`

**Comment by rababerladuseladim** [comment]
I bumped the version and will create a new release once this is merged into main.

Regarding testing, I do not really know how to address this. Running the reproduction step on main of mex-extractors will results in this bug. Updating mex-common to 0.24.0 introduces a whole lot of breaking changes, which Kamran is currently addressing in his [PR](https://github.com/robert-koch-institut/mex-extractors/pull/39). Hence, testing this is only possible after Kamran finishes his PR. I tested this manually by applying the changed to the installed version of mex-common in the mex-extractors venv.

**Review by erichesse — COMMENTED** [review]
test these changes, after tests are fixed in /pull/157 and PR is merged

**Comment by rababerladuseladim** [comment]
@erichesse Could you review again? I created a branch using this version of mex-common in mex-extractors for testing: https://github.com/robert-koch-institut/mex-extractors/pull/68

**Review by erichesse — APPROVED** [review]
Great! Looks good now

**Pull request merged**
