### PR TITLE
feature/mx-1455-document-ldap-extractor

### PR DESCRIPTION
**Pull request by rababerladuseladim**
This adds general documentation for the ldap extractor.

While reviewing the tests I noticed that they cover none of the convenience functions (ldap.extract). Should I create a ticket for that?

### CODE REVIEW

**Review by mr-kamran-ali — APPROVED** [review]
Very clear to me.

**Comment by mr-kamran-ali** [comment]
I think there should be tests for ldap.extract convenience functions. yes, please create a ticket.

**Comment by rababerladuseladim** [comment]
> I think there should be tests for ldap.extract convenience functions. yes, please create a ticket.

See https://jira.rki.local/browse/MX-1477

**Review by mr-kamran-ali — APPROVED** [review]

**Review by erichesse — COMMENTED** [review]
mex/common/ldap/README.md::line28ff

I'm irritated by the fact, that ldap.extract is described as a module for convenience functions only. the naming implies that the extract part of the ETL pipeline happens here. But actually that happens in ldap.connect.

if ldap.extract is for helper functions to build a mapping, maybe it should be rename to map.py or something. And ldap.connector should be renamed to ldap.extract.

I am open to other solutions, but right now, I find the structure to be misleading. 

Otherwise I like the README, good work

**Comment by rababerladuseladim** [comment]
That is indeed a point. I noticed that, too while writing the docs but did not know how to address this. Connectors are a common theme, so I'd rather leave the connector module untouched. Regarding the helper functions: In the organigram extractor these also reside in extract.py, hence I'd like to leave that in sync, too. One idea might be to add a new `utils.py` module and move any helper functionality in there. What do you think?

**Comment by erichesse** [comment]
yes, sound good to me

**Comment by rababerladuseladim** [comment]
I created a ticket: https://jira.rki.local/browse/MX-1479

**Pull request merged**
