### PR TITLE
Feature/mx 1497 resolve settings dependency cycle

### PR DESCRIPTION
**Pull request by carolinscholl**
This PR finishes the resolving of the settings dependency cycle. The previous PR was https://github.com/robert-koch-institut/mex-common/pull/49

In this PR, the now unnecessary echo-env-keys entrypoint and tests are removed.

### CODE REVIEW

**Review by cutoffthetop — CHANGES_REQUESTED** [review]
all good! could you update the mex-common version though, please?

**Comment by carolinscholl** [comment]
> all good! could you update the mex-common version though, please?



> all good! could you update the mex-common version though, please?

Do you mean update it to 0.16.1?

**Comment by cutoffthetop** [comment]
> Do you mean update it to 0.16.1?

yep

**Comment by carolinscholl** [comment]
> > Do you mean update it to 0.16.1?
> 
> yep

done!

**Pull request merged**
